# Generated by Django 5.2 on 2025-04-09 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Choose', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('matric_number', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('course_of_study', models.CharField(max_length=100)),
                ('year_of_graduation', models.IntegerField()),
                ('class_of_degree', models.CharField(choices=[('first class honours', 'First Class Honours'), ('second class honours (upper division)', 'Second Class Honours (Upper Division)'), ('second class honours (lower division)', 'Second Class Honours (Lower Division)'), ('third class honours', 'Third Class Honours'), ('pass', 'Pass')], help_text='Choose')),
                ('degree_awarded', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('remita_reference_number', models.CharField(max_length=12)),
                ('certificate_upload', models.FileField(help_text='Upload original scanned copy in PDF format.', upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('remita_reciept', models.FileField(help_text='Upload in PDF format.', upload_to='remita/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
