# Generated by Django 5.2 on 2025-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='matric_number',
            field=models.CharField(max_length=20),
        ),
    ]
