# Generated by Django 5.2 on 2025-05-03 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_application_matric_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='remita_reciept',
            new_name='remita_receipt',
        ),
        migrations.AddField(
            model_name='application',
            name='mode_of_collection',
            field=models.CharField(choices=[('email', 'Email'), ('hand collection', 'Hand Collection')], default='email', help_text='Select mode of collection', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_of_degree',
            field=models.CharField(choices=[('first class honours', 'First Class Honours'), ('second class honours (upper division)', 'Second Class Honours (Upper Division)'), ('second class honours (lower division)', 'Second Class Honours (Lower Division)'), ('third class honours', 'Third Class Honours'), ('pass', 'Pass')], help_text='Choose', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_graduation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
